name: Build Neutralino App

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and extract executable
      run: |
        # Build da imagem
        docker build -t neutralino-app .

        # Executar container e copiar resultado
        docker run --name temp-container neutralino-app
        docker cp temp-container:/app/dist ./
        docker rm temp-container

    - name: Check if executable exists
      run: |
        ls -la dist/
        # Verificar ambos os nomes possíveis
        if [ -f "kumite-win_x64.exe" ]; then
          echo "✅ Executable kumite-win_x64.exe found!"
          file dist/kumite-win_x64.exe
        else
          echo "❌ Executable not found!"
          echo "Available files in dist/:"
          ls -la dist/ || echo "dist/ directory not found"
          exit 1
        fi

    - name: Copy and rename executable
      run: |
        # Garantir que temos um arquivo kumite.exe para upload
        if [ -f "dist/kumite-win_x64.exe" ]; then
          cp dist/kumite-win_x64.exe dist/kumite.exe
          echo "✅ Copied kumite-win_x64.exe to kumite.exe"
        elif [ ! -f "dist/kumite.exe" ]; then
          echo "❌ No executable found to rename"
          exit 1
        fi

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: kumite-executable
        path: dist/kumite.exe
        retention-days: 30

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/kumite.exe
        token: ${{ secrets.GITHUB_TOKEN }}